apiVersion: v1
kind: Service 
metadata:
  name: frontend-svc
  namespace: default
  labels:
    tier: frontend
    app: frontend
    service: frontend
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-v1
  namespace: default
  labels:
    tier: frontend
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata: 
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: rxcore/frontend:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
 
